name: Build and test

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Build and push Docker image
          run: |
            docker build -t svelte-docker ../..
            echo "$DOCKER_USERNAME" | docker login -u "$DOCKER_PASSWORD" --password-stdin
            docker push my-docker-image